### ISSUE TITLE
 WP_API_Settings has changed to wpApiSettings

### ISSUE THREAD

**Issue by samwilson** [WP-API/docs-v2#101]
As of [11 January](https://github.com/WP-API/WP-API/commit/6a77c408b8bc09ae706fd8c396628e9c1d99682a#diff-22a405243ef29ff10e2237ec6d253b66) the  `WP_API_Settings` localised javascript object has changed to `wpApiSettings`. This should be added to the "what's changed" section in the docs. (I'd add it myself, but I'm sure someone else will know better than me.)

Thanks!

**Comment by danielbachhuber** [comment]
Huh. I'm not sure this was intentional. @adamsilverstein ?

**Comment by samwilson** [comment]
Ah, glad I mentioned it then! :) One of my projects got a bit broken from this change, so I've updated it. Let me know if you change it back again.

**Comment by adamsilverstein** [comment]
It was intentional, since the variable is used on the JavaScript side it was throwing warnings for not being camelCased (by the jscs linter). 

I'm always a bit confused which standard to follow (PHP or JS) when a variable is set up in PHP and passed to JS; I think using the JS naming convention is more appropriate as the variable is used once in PHP and multiple times on the JS side.  

Apologies for leaving that off the change log. Needs fixing in the docs.

**Comment by samwilson** [comment]
Thanks @adamsilverstein. :) I reckon you're right to change it. The all-caps thing always made it stand out a bit oddly in JS.

**Comment by adamsilverstein** [comment]
@samwilson Yea, after writing the last comment I surveyed existing WordPress core usage, and the clear standard is to use JS naming conventions (camelCase) when localizing variables. Apologies for any breaking change. Will correct in the docs so others don't run into the same pitfall.

**Comment by shankie-codes** [comment]
@adamsilverstein – I came across this when looking for an error that was introduced when I rebuilt my app. Couldn't agree with you more that it's a bit of a weird one how to write variables that are shared between languages!
